Repository Batatinha-s-Hardware/batatinhas-hardware, pull requests merged in 2020-08, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation, enhancement

#2 consertei os links do slide
  index.html
Labels: bug

#3 Menu jquery
  src/html/Computers/Netbooks.html
  src/html/Computers/Notbooks.html
  src/html/Computers/Printers.html
  src/html/HardWare/Coolers.html
  src/html/HardWare/HD.html
  src/html/HardWare/MemoryRAM.html
  src/html/HardWare/MotherBoards.html
  src/html/HardWare/Processor.html
  src/html/HardWare/VideoCards.html
  src/html/Peripherals/Mouse&Keybord.html
  src/html/Peripherals/PowerSouce.html
  src/html/Peripherals/Sound.html
  src/html/Portables/CellPhones.html
  src/html/Portables/Tablets.html
  src/html/menu.html
  src/js/products.js
Labels: documentation, enhancement

#4 Header
  global.css
  index.html
  src/html/Computers/Netbooks.html
  src/html/Computers/Notbooks.html
  src/html/Computers/Printers.html
  src/html/HardWare/Coolers.html
  src/html/HardWare/HD.html
  src/html/HardWare/MemoryRAM.html
  src/html/HardWare/MotherBoards.html
  src/html/HardWare/Processor.html
  src/html/HardWare/VideoCards.html
  src/html/Peripherals/Mouse&Keybord.html
  src/html/Peripherals/PowerSouce.html
  src/html/Peripherals/Sound.html
  src/html/Portables/CellPhones.html
  src/html/Portables/Tablets.html
  src/html/cadastro.html
  src/html/header.html
  src/js/products.js
Labels: enhancement

#5 Comentário removido.
  global.css
Labels: invalid

#7 estilizei os botões da div sobre
  global.css
Labels: documentation, enhancement

#9 informações dos celulares.
  src/html/Portables/CellPhones.html
Labels: documentation, enhancement

#8 Inserindo dados da página netbook
  src/html/Computers/Netbooks.html
Labels: documentation

#10 Logo antigo removido da "aba"
  src/html/Computers/Netbooks.html
  src/html/Computers/Notbooks.html
  src/html/Computers/Printers.html
  src/html/HardWare/Coolers.html
  src/html/HardWare/HD.html
  src/html/HardWare/MemoryRAM.html
  src/html/HardWare/MotherBoards.html
  src/html/HardWare/Processor.html
  src/html/HardWare/VideoCards.html
  src/html/Peripherals/Mouse&Keybord.html
  src/html/Peripherals/PowerSouce.html
  src/html/Peripherals/Sound.html
  src/html/Portables/CellPhones.html
Labels: enhancement

#12 Head externo
  src/html/Computers/Netbooks.html
  src/html/Computers/Notbooks.html
  src/html/Computers/Printers.html
  src/html/HardWare/Coolers.html
  src/html/HardWare/HD.html
  src/html/HardWare/MemoryRAM.html
  src/html/HardWare/MotherBoards.html
  src/html/HardWare/Processor.html
  src/html/HardWare/VideoCards.html
  src/html/Peripherals/Mouse&Keybord.html
  src/html/Peripherals/PowerSouce.html
  src/html/Peripherals/Sound.html
  src/html/Portables/CellPhones.html
  src/html/Portables/Tablets.html
  src/html/menu.html
Labels: enhancement

#13 Footer gitcolab
  src/js/footer.js
Labels: documentation, enhancement

#14 Footer externo
  global.css
  src/html/Computers/Netbooks.html
  src/html/Computers/Notbooks.html
  src/html/Computers/Printers.html
  src/html/HardWare/Coolers.html
  src/html/HardWare/HD.html
  src/html/HardWare/MemoryRAM.html
  src/html/HardWare/MotherBoards.html
  src/html/HardWare/Processor.html
  src/html/HardWare/VideoCards.html
  src/html/Peripherals/Mouse&Keybord.html
  src/html/Peripherals/PowerSouce.html
  src/html/Peripherals/Sound.html
  src/html/Portables/CellPhones.html
  src/html/cadastro.html
  src/html/footer.html
  src/js/products.js
Labels: documentation
