Repository Batatinha-s-Hardware/batatinhas-hardware, pull requests merged in 2020-09, with the labels that each got.

#16 Img
  assets/Computers/Notbooks/Acer/Notebook_Acer_Amd_4_N1.jpg
  assets/Computers/Notbooks/Apple/NotBook_Apple_3.jpg
  assets/Computers/Notbooks/Apple/NotBook_Apple_4.jpg
  assets/Computers/Notbooks/Asus/NotBook_Asus_4.jpg
  assets/Computers/Notbooks/HP/NotBook_HP_3.jpg
  assets/Computers/Notbooks/HP/NotBook_HP_4.jpg
  assets/Computers/Notbooks/LG/NotBook_LG_2.jpg
  assets/Computers/Notbooks/LG/NotBook_LG_3.jpg
  assets/Computers/Notbooks/LG/NotBook_LG_4.jpg
  assets/Computers/Notbooks/Lenovo/NotBook_Lenovo3.jpg
  assets/Computers/Notbooks/Lenovo/NotBook_Lenovo_2.jpg
  assets/Computers/Notbooks/Lenovo/NotBook_Lenovo_4.jpg
  assets/Computers/Notbooks/Megaware/Megaware_Slim.jpg
  assets/Computers/Notbooks/Positivo/Positivo_Motion.jpg
  assets/Computers/Notbooks/Samsung/Samsung_Flash_Intel_ Celeron.jpg
  assets/Computers/Notbooks/Samsung/Samsung_Flash_Intel_ Celeron_2.jpg
  assets/Hardware/HD_SSD/Kings/kingston.jpg
  assets/Hardware/HD_SSD/Kings/kingston2.jpg
  assets/Hardware/HD_SSD/SeaG/barracuda.jpg
  assets/Hardware/HD_SSD/SeaG/barracuda2.jpg
  assets/Hardware/HD_SSD/WD/Purple.jpg
  assets/Hardware/HD_SSD/WD/Purple2.jpg
  assets/Hardware/PlacaM/AsRock/Asrock_320M.jpg
  assets/Hardware/PlacaM/Asus/placa-mae-asus-prime-x299-a-ii-intel-lga-2066-atx-ddr4-_placa-mae-asus-prime-x299-a-ii-intel-lga-2066-atx-ddr4-_1570567692_gg.jpg
  assets/Hardware/PlacaM/Asus/placa-mae-asus-prime-x299-a-ii-intel-lga-2066-atx-ddr4-_placa-mae-asus-prime-x299-a-ii-intel-lga-2066-atx-ddr4-_1570567695_gg.jpg
  assets/Hardware/PlacaM/Gigabyte/placa-m_e-asus-h310m-plus-tuf-gaming_4_.jpg
  assets/Hardware/PlacaM/Gigabyte/placa-mae-gigabyte-b365m-ds3h-intel-lga-1151-matx-ddr4_placa-mae-gigabyte-b365m-ds3h-intel-lga-1151-matx-ddr4_1566828957_gg.jpg
  assets/Hardware/PlacaV/Galax/NVIDIA_GeForce_GTX_1660.jpg
  assets/Hardware/PlacaV/GigaByte/gigabyteNvidia3.jpg
  assets/Hardware/PlacaV/GigaByte/gigabyteRadeon3.jpg
  assets/Hardware/PlacaV/MSI/MSI_AMD_Radeon_RX_570_2.jpg
  assets/Hardware/PlacaV/MSI/MSI_AMD_Radeon_RX_570_4G.jpg
  assets/Hardware/PlacaV/MSI/MSI_NVIDIA_GeForce_GT 710_2GB.jpg
  assets/Hardware/Process/Amd/amd_fx.jpg
  assets/Hardware/Process/Amd/amd_rhyzen.jpg
  assets/Hardware/Process/Intel/intel_celeron.jpg
  assets/Hardware/RAM/CRS/Cmv8gx3m1a1333c9_Corsair.jpg
  assets/Hardware/RAM/CRS/Cmv8gx3m1a1333c9_Corsair2.jpg
  assets/Hardware/RAM/CRS/Cmv8gx3m1a1333c9_Corsair3.jpg
  assets/Hardware/RAM/CRS/Memoria_RAM_DDR4_1.jpg
  assets/Hardware/RAM/CRS/Memoria_RAM_DDR4_2.jpg
  assets/Hardware/RAM/CRS/Memoria_RAM_DDR4_3.jpg
  assets/Hardware/RAM/HPX/Memoria_HyperX_Fury.jpg
  assets/Hardware/RAM/HPX/Memoria_HyperX_Fury2.jpg
  assets/Hardware/RAM/HPX/Memoria_HyperX_Fury3.jpg
  assets/Portables/CellPhone/LG/LG_G8S_3.jpg
  assets/Portables/CellPhone/Motorola/MotoG8.jpg
  assets/Portables/CellPhone/Multilaser/Multilaser.jpg
  assets/Portables/CellPhone/Quantum/cielo.jpg
  assets/Portables/CellPhone/Samsung/Note10.jpg
  assets/Portables/CellPhone/Xiaome/Xiaomi.jpg
  assets/Portables/CellPhone/iPhone/Iphone11.jpg
  src/html/HardWare/Processor.html
Labels: documentation

#18 voltei para o menu antigo
  index.html
Labels: bug

#19 consertei o menu na página home
  index.html
Labels: bug

#27 Coolers Imagens
  src/html/HardWare/Coolers.html
Labels: content

#25 Processadores Imagens
  src/html/HardWare/Processor.html
Labels: content

#23 Celulares Imagens
  src/html/Portables/CellPhones.html
Labels: content

#24 Notbooks Imagens
  src/html/Computers/Notbooks.html
Labels: content

#29 feature/cadastro-menu
  src/html/cadastro.html
Labels: content, feature, layout
